### ISSUE TITLE
register this pkg?

### ISSUE THREAD

**Issue by bjarthur** [JuliaGraphics/FreeTypeAbstraction.jl#10]
`FreeType` is registered, but not `FreeTypeAbstraction`.  would it make sense to do so now that it's in `JuliaGraphics`?

**Comment by SimonDanisch** [comment]
Yes! I just need to figure out what to do about https://github.com/JuliaGraphics/FreeTypeAbstraction.jl/pull/8

Would you mind reviewing it?

**Comment by bjarthur** [comment]
closed by https://github.com/JuliaLang/METADATA.jl/pull/10202
