### ISSUE TITLE
FreeTypeAbstraction v0.6 not compatible with FreeType v2

### ISSUE THREAD

**Issue by jaakkor2** [JuliaGraphics/FreeTypeAbstraction.jl#36]
FWIW,
https://github.com/JuliaGraphics/FreeTypeAbstraction.jl/blob/v0.6.0/Project.toml
claims `FreeType = "2, 3"`, but is using `FreeType.LibFreeType` on line
https://github.com/JuliaGraphics/FreeTypeAbstraction.jl/blob/v0.6.0/src/types.jl#L152

That is only available in FreeType v3 since
https://github.com/JuliaGraphics/FreeType.jl/blob/v3.0.0/src/FreeType.jl#L4
says `using .LibFreeType`.

**Comment by SimonDanisch** [comment]
Oh good catch!

**Comment by SimonDanisch** [comment]
Fixed in: https://github.com/JuliaGraphics/FreeTypeAbstraction.jl/commit/458ccf9ead44bc471bebf482c8eb0933aed88b90
